# serene v5.5.0
#
# - docs: https://github.com/isunjn/serene/blob/latest/USAGE.md
# - check for updates: https://github.com/isunjn/serene/releases
#
#=========================================================================================

base_url = "https://isgin01.github.io"
title = "isgin01's personal website"
description = "I like books, mathematics, programming, and languages."
default_language = "en"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = false # Keep this false, as it may cause issues with some styles
build_search_index = false # Keep this false, search is temporarily unsupported
generate_feeds = false # Whether to generate a feed file in root, read docs for more info about rss feed
feed_filenames = [
  "feed.xml",
] # "feed.xml" | "atom.xml" | "rss.xml", read docs for more info
# taxonomies = [{ name = "tags" }, { name = "categories" }]

# New
[markdown]
github_alerts = false # optional, enables GitHub-style callout syntax
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false


[markdown.highlighting]
style = "class"
light_theme = "github-light"  # or any zola built-in theme
dark_theme = "github-dark"    # or any zola built-in theme

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

sections = [
  { name = "hireme", path = "/hireme", is_external = false },
  { name = "posts", path = "/posts", is_external = false },
]
blog_section_path = "/posts"

back_link_text = "Back" # Text of the back button
force_theme = false     # false | "light" | "dark"

# footer_copyright = "© 2025 isgin01"
footer_copyright = ""
footer_credits = false # Whether to show "Built with zola and serene" in footer

not_found_error_text = "404 Not Found"
not_found_recover_text = "« back to home »"

reaction = false                                       # Whether to enable anonymous emoji reactions (Note: You need to set up a working api endpoint to enable this feature)
reaction_align = "right"                               # "left" | "center" | "right"
reaction_endpoint = "https://example.com/api/reaction"
